#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and on web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
sudo apt update
# install nginx packages
sudo apt install nginx -y
# allow request through port 80
sudo ufw allow 'Nginx HTTP'
# start nginx
sudo service nginx start
# set www directory owner
sudo chown -R "$USER":"$USER" /var/www
# set default response file
echo 'Hello World!' > /var/www/html/index.html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/
sudo sed -i "/server_name _;/c\ \tserver_name _;\n\tadd_header X-Served-By \$hostname;\n" /etc/nginx/sites-available/default
# restart nginx
sudo service nginx restart
