#!/usr/bin/env bash
# Creating a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.

sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  JPOkey-frontend
        bind *:80
        mode http
        default_backend JPOkey-backend
backend JPOkey-backend
        balance roundrobin
        server 147163-web-01 54.90.44.187:80 check
        server 147163-web-02 35.175.128.62:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
