#!/usr/bin/env bash
# debugging nginx port 80
# This is how I solved it: delete the existing ../sites-enabled/default and replace it with a copy of
# ../sites-available/default. I did that by creating a symbolic link. 
# Please Note: The flag -s creates a symbolic link, -f deletes the existing file and replaces it
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
